### ISSUE TITLE
Example doesn't work on iPad pro

### ISSUE THREAD

**Issue by stevemao** [cht8687/react-expandable-listview#1]

**Comment by cht8687** [comment]
hi @stevemao, could you elaborate more details?

**Comment by waleedarshad-vf** [comment]
How to use it in android app. instructions are not clear, where we are importing?

**Comment by cht8687** [comment]
@waleedarshad-vf  is that WebView android project? if so, I think it would work. 
Could you put more insights on how to improve the doc? PR is welcome. :smile:

**Comment by waleedarshad-vf** [comment]
you are right :)

**Comment by waleedarshad-vf** [comment]
you must write this one for react-native as well if you have any experiece :)

**Comment by cht8687** [comment]
@waleedarshad-vf  as far as I knows, react-native does have it's own sticky header library. You can check their documentation.

**Comment by waleedarshad-vf** [comment]
you are pointing to this? https://www.npmjs.com/package/react-native-parallax-scroll-view?

**Comment by cht8687** [comment]
@waleedarshad-vf  this will do:

https://github.com/cht8687/RN/blob/master/TrackWorkNSW/app/components/Incomming.js#L45-L98

it's built-in functionality in RN.

**Comment by waleedarshad-vf** [comment]
@cht8687 Thanks! i will try this and let you know.
