### ISSUE TITLE
Appears to mutate state

### ISSUE THREAD

**Issue by webOS101** [cht8687/react-expandable-listview#4]
It looks like https://github.com/cht8687/react-expandable-listview/blob/master/src/ReactExpandableListView.js#L91 mutates the previous state. Wouldn't you normally want to modify the state after you make a clone of it or am I missing something?

**Comment by cht8687** [comment]
Hi, I am changing the state so the UI will have the open/collapse effect. Do you have other good suggestion here?

**Comment by webOS101** [comment]
Well, I'm not a React guru (yet), I was thinking maybe something like:

```
const newData = Object.assign({}, this.state)
newData[headerIndex].isOpened = !newData[headerIndex].isOpened
this.setState(newData)
```

Then you're not directly modifying `this.state`.

**Comment by stevemao** [comment]
@webOS101 Correct, PR welcome :)

**Comment by cht8687** [comment]
@webOS101  You are 100% right. This should be changed.

**Comment by cht8687** [comment]
@webOS101  thank you! I've fixed this.
