### ISSUE TITLE
It doesn't expand in Safari.

### ISSUE THREAD

**Issue by dalianmao22233** [cht8687/react-expandable-listview#6]
I don't know why it doesn't perform animation in Safari, but it can work well in Chrome and Firefox.
Thank you for your brilliant work!

**Comment by dalianmao22233** [comment]
I fix it by add following code:<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-shim.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-sham.min.js"></script><script src="https://wzrd.in/standalone/es7-shim@latest"></script>

**Comment by cht8687** [comment]
Hi @dalianmao22233,  could u share your code? "maybe u can submit  a pull  request 👍
