### ISSUE TITLE
Can we use this to work with React-Native-Router-Flex?

### ISSUE THREAD

**Issue by Ian-An** [cht8687/react-expandable-listview#8]
is there a way that we use this to work with React-Native-Router-Flex?
Thank you.

**Comment by cht8687** [comment]
Hi @Ian999777 , as long as you send in the children as React components, it should work. do you get any errors?

**Comment by stevemao** [comment]
@Ian999777 what exactly is the issue you are experiencing?

**Comment by rohananarse** [comment]
hi would like to know can i route to other pages from collapsed list items ..???
